// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/metrics/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Health int32

const (
	Health_HEALTH_UNSPECIFIED Health = 0
	Health_HEALTH_OK          Health = 1
	Health_HEALTH_NOT_OK      Health = 2
	Health_HEALTH_EVALUATING  Health = 3
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_OK",
		2: "HEALTH_NOT_OK",
		3: "HEALTH_EVALUATING",
	}
	Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED": 0,
		"HEALTH_OK":          1,
		"HEALTH_NOT_OK":      2,
		"HEALTH_EVALUATING":  3,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_metrics_proto_metrics_proto_enumTypes[0].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_internal_metrics_proto_metrics_proto_enumTypes[0]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_internal_metrics_proto_metrics_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_metrics_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metrics_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_metrics_proto_metrics_proto_rawDescGZIP(), []int{0}
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumServers    int64                  `protobuf:"varint,1,opt,name=numServers,proto3" json:"numServers,omitempty"`
	TotalRequests int64                  `protobuf:"varint,2,opt,name=totalRequests,proto3" json:"totalRequests,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ServerHealth  []Health               `protobuf:"varint,4,rep,packed,name=serverHealth,proto3,enum=metrics.Health" json:"serverHealth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_internal_metrics_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metrics_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_internal_metrics_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetNumServers() int64 {
	if x != nil {
		return x.NumServers
	}
	return 0
}

func (x *Metrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *Metrics) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Metrics) GetServerHealth() []Health {
	if x != nil {
		return x.ServerHealth
	}
	return nil
}

var File_internal_metrics_proto_metrics_proto protoreflect.FileDescriptor

const file_internal_metrics_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"$internal/metrics/proto/metrics.proto\x12\ametrics\"\a\n" +
	"\x05Empty\"\xa2\x01\n" +
	"\aMetrics\x12\x1e\n" +
	"\n" +
	"numServers\x18\x01 \x01(\x03R\n" +
	"numServers\x12$\n" +
	"\rtotalRequests\x18\x02 \x01(\x03R\rtotalRequests\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x123\n" +
	"\fserverHealth\x18\x04 \x03(\x0e2\x0f.metrics.HealthR\fserverHealth*Y\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHEALTH_OK\x10\x01\x12\x11\n" +
	"\rHEALTH_NOT_OK\x10\x02\x12\x15\n" +
	"\x11HEALTH_EVALUATING\x10\x032<\n" +
	"\n" +
	"AppMetrics\x12.\n" +
	"\n" +
	"GetMetrics\x12\x0e.metrics.Empty\x1a\x10.metrics.MetricsB\tZ\a./protob\x06proto3"

var (
	file_internal_metrics_proto_metrics_proto_rawDescOnce sync.Once
	file_internal_metrics_proto_metrics_proto_rawDescData []byte
)

func file_internal_metrics_proto_metrics_proto_rawDescGZIP() []byte {
	file_internal_metrics_proto_metrics_proto_rawDescOnce.Do(func() {
		file_internal_metrics_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_metrics_proto_metrics_proto_rawDesc), len(file_internal_metrics_proto_metrics_proto_rawDesc)))
	})
	return file_internal_metrics_proto_metrics_proto_rawDescData
}

var file_internal_metrics_proto_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_metrics_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_metrics_proto_metrics_proto_goTypes = []any{
	(Health)(0),     // 0: metrics.Health
	(*Empty)(nil),   // 1: metrics.Empty
	(*Metrics)(nil), // 2: metrics.Metrics
}
var file_internal_metrics_proto_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.Metrics.serverHealth:type_name -> metrics.Health
	1, // 1: metrics.AppMetrics.GetMetrics:input_type -> metrics.Empty
	2, // 2: metrics.AppMetrics.GetMetrics:output_type -> metrics.Metrics
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_metrics_proto_metrics_proto_init() }
func file_internal_metrics_proto_metrics_proto_init() {
	if File_internal_metrics_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_metrics_proto_metrics_proto_rawDesc), len(file_internal_metrics_proto_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_metrics_proto_metrics_proto_goTypes,
		DependencyIndexes: file_internal_metrics_proto_metrics_proto_depIdxs,
		EnumInfos:         file_internal_metrics_proto_metrics_proto_enumTypes,
		MessageInfos:      file_internal_metrics_proto_metrics_proto_msgTypes,
	}.Build()
	File_internal_metrics_proto_metrics_proto = out.File
	file_internal_metrics_proto_metrics_proto_goTypes = nil
	file_internal_metrics_proto_metrics_proto_depIdxs = nil
}
