// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: internal/metrics/proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppMetrics_GetMetrics_FullMethodName = "/metrics.AppMetrics/GetMetrics"
)

// AppMetricsClient is the client API for AppMetrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppMetricsClient interface {
	GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metrics, error)
}

type appMetricsClient struct {
	cc grpc.ClientConnInterface
}

func NewAppMetricsClient(cc grpc.ClientConnInterface) AppMetricsClient {
	return &appMetricsClient{cc}
}

func (c *appMetricsClient) GetMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Metrics)
	err := c.cc.Invoke(ctx, AppMetrics_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMetricsServer is the server API for AppMetrics service.
// All implementations must embed UnimplementedAppMetricsServer
// for forward compatibility.
type AppMetricsServer interface {
	GetMetrics(context.Context, *Empty) (*Metrics, error)
	mustEmbedUnimplementedAppMetricsServer()
}

// UnimplementedAppMetricsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppMetricsServer struct{}

func (UnimplementedAppMetricsServer) GetMetrics(context.Context, *Empty) (*Metrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedAppMetricsServer) mustEmbedUnimplementedAppMetricsServer() {}
func (UnimplementedAppMetricsServer) testEmbeddedByValue()                    {}

// UnsafeAppMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppMetricsServer will
// result in compilation errors.
type UnsafeAppMetricsServer interface {
	mustEmbedUnimplementedAppMetricsServer()
}

func RegisterAppMetricsServer(s grpc.ServiceRegistrar, srv AppMetricsServer) {
	// If the following call panics, it indicates UnimplementedAppMetricsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppMetrics_ServiceDesc, srv)
}

func _AppMetrics_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMetricsServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMetrics_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMetricsServer).GetMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AppMetrics_ServiceDesc is the grpc.ServiceDesc for AppMetrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppMetrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.AppMetrics",
	HandlerType: (*AppMetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetrics",
			Handler:    _AppMetrics_GetMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/metrics/proto/metrics.proto",
}
